export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";

export const PURCHASE_TRUE = "PURCHASE_TRUE";
export const PURCHASE_FALSE = "PURCHASE_FALSE";
export const IS_PURCHASABLE = "IS_PURCHASABLE";
export const PURCHASING_FINISH = "PURCHASING_FINISH";

export const GET_INGREDIENTS = "GET_INGREDIENTS";
export const FAILED_TO_GET_INGREDIENTS = "FAILED_TO_GET_INGREDIENTS";


export const PURCHASE_BURGER_SUCCESS = "PURCHASE_BURGER_SUCCESS";
export const PURCHASE_BURGER_FAIL = "PURCHASE_BURGER_FAIL" ;
export const FETCH_ORDERS_SUCCESS = "FETCH_ORDERS_SUCCESS";
export const FETCH_ORDERS_FAILED = " FETCH_ORDERS_FAILED";
export const PURCHASE_INIT = "PURCHASE_INIT";
